mv templates/defaultxmlns1 templates/default-xmlns; mv references/defaultxmlns1.txt references/default-xmlns.txt
mv templates/encodingbuiltins templates/encoding-builtins; mv references/encodingbuiltins.txt references/encoding-builtins.txt
mv templates/listiterators templates/iterators; mv references/listiterators.txt references/iterators.txt
mv templates/extlist templates/list; mv references/extlist.txt references/list.txt
mv templates/local templates/localization; mv references/local.txt references/localization.txt
mv templates/loopvar templates/loopvariable; mv references/loopvar.txt references/loopvariable.txt
mv templates/function templates/macros; mv references/function.txt references/macros.txt
mv templates/macro templates/macros2; mv references/macro.txt references/macros2.txt
mv templates/models templates/multimodels; mv references/models.txt references/multimodels.txt
mv templates/nested1 templates/nested; mv references/nested1.txt references/nested.txt
mv templates/numberformat templates/number-format; mv references/numberformat.txt references/number-format.txt
mv templates/numberliteral templates/number-literal; mv references/numberliteral.txt references/number-literal.txt
mv templates/numericalcast templates/numerical-cast; mv references/numericalcast.txt references/numerical-cast.txt
mv templates/outputencoding1 templates/output-encoding1; mv references/outputencoding1.txt references/output-encoding1.txt
mv templates/outputencoding2 templates/output-encoding2; mv references/outputencoding2.txt references/output-encoding2.txt
mv templates/outputencoding3 templates/output-encoding3; mv references/outputencoding3.txt references/output-encoding3.txt
mv templates/stringbuiltins templates/string-builtins1; mv references/stringbuiltins.txt references/string-builtins1.txt
mv templates/stringbuiltins2 templates/string-builtins2; mv references/stringbuiltins2.txt references/string-builtins2.txt
mv templates/transformation templates/transforms; mv references/transformation.txt references/transforms.txt
mv templates/typebuiltins templates/type-builtins; mv references/typebuiltins.txt references/type-builtins.txt
mv templates/varlayers templates/var-layers; mv references/varlayers.txt references/var-layers.txt
mv templates/wstrim templates/whitespace-trim; mv references/wstrim.txt references/whitespace-trim.txt
mv templates/wsstripinheader templates/wstrip-in-header; mv references/wsstripinheader.txt references/wstrip-in-header.txt
mv templates/xmlfragment templates/xml-fragment; mv references/xmlfragment.txt references/xml-fragment.txt
mv templates/xmlns templates/xmlns1; mv references/xmlns.txt references/xmlns1.txt
